{% set name = "monet" %}
{% set version = "2.2.1" %}

package:
  name: monet
  version: {{ version }}

source:
  url: https://github.com/noaa-oar-arl/MONET/archive/v{{ version }}.tar.gz
  sha256: 173b4747389041bf33cc05965712cc7bf1a9537e69fe8d46cfd7b9810630a936

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas
    - xarray
    - dask
    - cartopy
    - matplotlib-base
    - seaborn
    - pyresample
    - python-stratify
    - pydecorate
    - xesmf  # [not win]
test:
  imports:
    - monet
    - monet.plots
    - monet.util

about:
  home: https://github.com/noaa-oar-arl/monet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The Model and ObservatioN Evaluation Tool - for meteorology and AQ
  doc_url: https://monet-arl.readthedocs.io

extra:
  recipe-maintainers:
    - bbakernoaa
